// Generated by Dagger (https://dagger.dev).
package com.example.exchangerates.presentation.dialog.calculateBottomFragment;

import com.example.exchangerates.domain.usecase.MakeDbSpecificDataUseCase;
import com.example.exchangerates.domain.usecase.MakeDeleteSingeDataInfoDbUseCase;
import com.example.exchangerates.domain.usecase.MakeSingleInsertDbDataUseCase;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class BottomSheetViewModel_Factory implements Factory<BottomSheetViewModel> {
  private final Provider<MakeDbSpecificDataUseCase> makeDbSpecificDataUseCaseProvider;

  private final Provider<MakeSingleInsertDbDataUseCase> makeSingleInsertDbDataUseCaseProvider;

  private final Provider<MakeDeleteSingeDataInfoDbUseCase> makeDeleteSingeDataInfoDbUseCaseProvider;

  public BottomSheetViewModel_Factory(
      Provider<MakeDbSpecificDataUseCase> makeDbSpecificDataUseCaseProvider,
      Provider<MakeSingleInsertDbDataUseCase> makeSingleInsertDbDataUseCaseProvider,
      Provider<MakeDeleteSingeDataInfoDbUseCase> makeDeleteSingeDataInfoDbUseCaseProvider) {
    this.makeDbSpecificDataUseCaseProvider = makeDbSpecificDataUseCaseProvider;
    this.makeSingleInsertDbDataUseCaseProvider = makeSingleInsertDbDataUseCaseProvider;
    this.makeDeleteSingeDataInfoDbUseCaseProvider = makeDeleteSingeDataInfoDbUseCaseProvider;
  }

  @Override
  public BottomSheetViewModel get() {
    return newInstance(makeDbSpecificDataUseCaseProvider.get(), makeSingleInsertDbDataUseCaseProvider.get(), makeDeleteSingeDataInfoDbUseCaseProvider.get());
  }

  public static BottomSheetViewModel_Factory create(
      Provider<MakeDbSpecificDataUseCase> makeDbSpecificDataUseCaseProvider,
      Provider<MakeSingleInsertDbDataUseCase> makeSingleInsertDbDataUseCaseProvider,
      Provider<MakeDeleteSingeDataInfoDbUseCase> makeDeleteSingeDataInfoDbUseCaseProvider) {
    return new BottomSheetViewModel_Factory(makeDbSpecificDataUseCaseProvider, makeSingleInsertDbDataUseCaseProvider, makeDeleteSingeDataInfoDbUseCaseProvider);
  }

  public static BottomSheetViewModel newInstance(
      MakeDbSpecificDataUseCase makeDbSpecificDataUseCase,
      MakeSingleInsertDbDataUseCase makeSingleInsertDbDataUseCase,
      MakeDeleteSingeDataInfoDbUseCase makeDeleteSingeDataInfoDbUseCase) {
    return new BottomSheetViewModel(makeDbSpecificDataUseCase, makeSingleInsertDbDataUseCase, makeDeleteSingeDataInfoDbUseCase);
  }
}
