// Generated by Dagger (https://dagger.dev).
package com.example.exchangerates.presentation.dialog.calculateBottomFragment;

import com.example.exchangerates.app.di.utils.ViewModelFactory;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class CalculateBottomSheetFragment_MembersInjector implements MembersInjector<CalculateBottomSheetFragment> {
  private final Provider<ViewModelFactory> viewModelFactoryProvider;

  private final Provider<DispatchingAndroidInjector<Object>> androidInjectorProvider;

  public CalculateBottomSheetFragment_MembersInjector(
      Provider<ViewModelFactory> viewModelFactoryProvider,
      Provider<DispatchingAndroidInjector<Object>> androidInjectorProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
    this.androidInjectorProvider = androidInjectorProvider;
  }

  public static MembersInjector<CalculateBottomSheetFragment> create(
      Provider<ViewModelFactory> viewModelFactoryProvider,
      Provider<DispatchingAndroidInjector<Object>> androidInjectorProvider) {
    return new CalculateBottomSheetFragment_MembersInjector(viewModelFactoryProvider, androidInjectorProvider);
  }

  @Override
  public void injectMembers(CalculateBottomSheetFragment instance) {
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
    injectAndroidInjector(instance, androidInjectorProvider.get());
  }

  @InjectedFieldSignature("com.example.exchangerates.presentation.dialog.calculateBottomFragment.CalculateBottomSheetFragment.viewModelFactory")
  public static void injectViewModelFactory(CalculateBottomSheetFragment instance,
      ViewModelFactory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }

  @InjectedFieldSignature("com.example.exchangerates.presentation.dialog.calculateBottomFragment.CalculateBottomSheetFragment.androidInjector")
  public static void injectAndroidInjector(CalculateBottomSheetFragment instance,
      DispatchingAndroidInjector<Object> androidInjector) {
    instance.androidInjector = androidInjector;
  }
}
