// Generated by Dagger (https://dagger.dev).
package com.example.exchangerates.app.di.module;

import com.example.exchangerates.domain.repository.RepositoryExchangeRates;
import com.example.exchangerates.domain.usecase.MakeApiUseCase;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class RepositoryModule_MakeApiUseCaseFactory implements Factory<MakeApiUseCase> {
  private final RepositoryModule module;

  private final Provider<RepositoryExchangeRates> repositoryProvider;

  public RepositoryModule_MakeApiUseCaseFactory(RepositoryModule module,
      Provider<RepositoryExchangeRates> repositoryProvider) {
    this.module = module;
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public MakeApiUseCase get() {
    return makeApiUseCase(module, repositoryProvider.get());
  }

  public static RepositoryModule_MakeApiUseCaseFactory create(RepositoryModule module,
      Provider<RepositoryExchangeRates> repositoryProvider) {
    return new RepositoryModule_MakeApiUseCaseFactory(module, repositoryProvider);
  }

  public static MakeApiUseCase makeApiUseCase(RepositoryModule instance,
      RepositoryExchangeRates repository) {
    return Preconditions.checkNotNullFromProvides(instance.makeApiUseCase(repository));
  }
}
