// Generated by Dagger (https://dagger.dev).
package com.example.exchangerates.app.di.module;

import com.example.exchangerates.domain.repository.RepositoryExchangeRates;
import com.example.exchangerates.domain.usecase.MakeDeleteSingeDataInfoDbUseCase;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class RepositoryModule_MakeDeleteSingeDataInfoDbUseCaseFactory implements Factory<MakeDeleteSingeDataInfoDbUseCase> {
  private final RepositoryModule module;

  private final Provider<RepositoryExchangeRates> repositoryProvider;

  public RepositoryModule_MakeDeleteSingeDataInfoDbUseCaseFactory(RepositoryModule module,
      Provider<RepositoryExchangeRates> repositoryProvider) {
    this.module = module;
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public MakeDeleteSingeDataInfoDbUseCase get() {
    return makeDeleteSingeDataInfoDbUseCase(module, repositoryProvider.get());
  }

  public static RepositoryModule_MakeDeleteSingeDataInfoDbUseCaseFactory create(
      RepositoryModule module, Provider<RepositoryExchangeRates> repositoryProvider) {
    return new RepositoryModule_MakeDeleteSingeDataInfoDbUseCaseFactory(module, repositoryProvider);
  }

  public static MakeDeleteSingeDataInfoDbUseCase makeDeleteSingeDataInfoDbUseCase(
      RepositoryModule instance, RepositoryExchangeRates repository) {
    return Preconditions.checkNotNullFromProvides(instance.makeDeleteSingeDataInfoDbUseCase(repository));
  }
}
