// Generated by Dagger (https://dagger.dev).
package com.example.exchangerates.app.di.module;

import com.example.exchangerates.domain.repository.RepositoryExchangeRates;
import com.example.exchangerates.domain.usecase.MakeDbDataUseCase;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class RepositoryModule_MakeDbDataUseCaseFactory implements Factory<MakeDbDataUseCase> {
  private final RepositoryModule module;

  private final Provider<RepositoryExchangeRates> repositoryProvider;

  public RepositoryModule_MakeDbDataUseCaseFactory(RepositoryModule module,
      Provider<RepositoryExchangeRates> repositoryProvider) {
    this.module = module;
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public MakeDbDataUseCase get() {
    return makeDbDataUseCase(module, repositoryProvider.get());
  }

  public static RepositoryModule_MakeDbDataUseCaseFactory create(RepositoryModule module,
      Provider<RepositoryExchangeRates> repositoryProvider) {
    return new RepositoryModule_MakeDbDataUseCaseFactory(module, repositoryProvider);
  }

  public static MakeDbDataUseCase makeDbDataUseCase(RepositoryModule instance,
      RepositoryExchangeRates repository) {
    return Preconditions.checkNotNullFromProvides(instance.makeDbDataUseCase(repository));
  }
}
