// Generated by Dagger (https://dagger.dev).
package com.example.exchangerates.app.di.module;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import retrofit2.Retrofit;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class RetrofiteModule_CreateRetrofiteFactory implements Factory<Retrofit> {
  private final RetrofiteModule module;

  public RetrofiteModule_CreateRetrofiteFactory(RetrofiteModule module) {
    this.module = module;
  }

  @Override
  public Retrofit get() {
    return createRetrofite(module);
  }

  public static RetrofiteModule_CreateRetrofiteFactory create(RetrofiteModule module) {
    return new RetrofiteModule_CreateRetrofiteFactory(module);
  }

  public static Retrofit createRetrofite(RetrofiteModule instance) {
    return Preconditions.checkNotNullFromProvides(instance.createRetrofite());
  }
}
